services:
  - type: web
    name: django-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn departments.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12.3
